### ISSUE TITLE
PHP 5.3

### ISSUE THREAD

**Issue by Kanti** [codeclimate/php-test-reporter#59]
The [composer.json](https://github.com/codeclimate/php-test-reporter/blob/master/composer.json#L19) says that the current master ist php 5.3 ready.
But the code fails in my [travis](https://travis-ci.org/Kanti/hub-updater/jobs/148642129#L376) Build in php version 5.3, because of this:
https://github.com/codeclimate/php-test-reporter/blob/master/composer/bin/test-reporter#L8

``` php
$files = [
    __DIR__ . '/../../vendor/autoload.php',
    __DIR__ . '/../../../../autoload.php',
];
```

this is so since: [4071b3b](https://github.com/codeclimate/php-test-reporter/commit/4071b3b26443a83983740002f9aa8123fa72e522)

**Comment by wfleming** [comment]
Thanks for the report, @Kanti, and sorry for the issue. We're in the midst of doing some refactoring & modernizing of this project's codebase, and are developing/testing against PHP 5.5, so this wasn't caught during testing, sorry.

We'll look into addressing this, but in the meantime would it work for you to use the last tagged version `v0.3.2` instead of `master`?

**Comment by Kanti** [comment]
I did use the v0.1.2 and it worked again :D

**Comment by pbrisbin** [comment]
It [looks like](http://php.net/supported-versions.php) PHP <=5.5 have all been EOLd, so I would advocate changing the version bounds to only support >=5.6, as well as updating our test suite to run against that (it appears to run with 5.5 right now).

**Comment by ziodave** [comment]
Hello, in our case we still need PHP 5.3+, because we develop a plugin for WordPress which still sees [a broad usage of PHP 5.3 and 5.4](https://wordpress.org/about/stats/): 43% of WordPress web sites run on PHP 5.3/5.4.

Our [unit tests](https://travis-ci.org/insideout10/wordlift-plugin/builds/191259963) would fail w/o such support.

May I ask you to reconsider the minimum PHP requirement?

**Comment by localheinz** [comment]
@ziodave 

How about using an older version of `codeclimate/php-test-reporter` that still supports PHP 5.3?

Take a look at https://packagist.org/packages/codeclimate/php-test-reporter!

**Comment by ziodave** [comment]
Hello @localheinz, yeah, I downgraded to 0.4.x :-) I am just afraid one day it'll be unsupported.

**Comment by Bonscho** [comment]
Because the reporter usually runs on automated test or ci environments like travis, it definitively should support older versions of PHP. Wich version is available depends on the test environment and it should be possible to run tests on older platforms and PHP versions. 

_Example:_ We develop a library and run automated tests on Travis that cover versions from PHP 5.4 up to 7.1. All tests are fine, but the test on PHP 5.3 fails because the test reporter could not get installed vai composer.

**Comment by maxjacobson** [comment]
@Bonscho for some context, [this](https://github.com/codeclimate/php-test-reporter/pull/92#issuecomment-271925101) is where we formally dropped support, but looks like it was dropped because it wasn't working on that version. If it's easy enough to keep it working for 5.3, we wouldn't object to doing that, but I'm not sure when we'll have time to look into those errors -- I'd be happy to look at a PR which fixed those errors and re-added support

**Comment by localheinz** [comment]
I'll take a look later!

**Comment by XedinUnknown** [comment]
@ziodave, depending on `^0.4` wouldn't work, because `0.4.2` requires PHP at `^5.5`.

Gentlemen, why didn't this BC-breaking release increment the minor version number, please?

**Comment by XedinUnknown** [comment]
If changes like this are going to be made in the future (most likely), I believe it is unwise to recommend depending on `dev-master` in the docs; `^0.4` would be more appropriate, but would require following SemVer, which this latest release apparently didn't. I now have 30 projects to change `dev-master` to `<=0.4.1` in.

**Comment by XedinUnknown** [comment]
Version `0.4.1` that [requires](https://github.com/codeclimate/php-test-reporter/blob/v0.4.1/composer.json#L22) PHP `>=5.3` is [actually](https://github.com/codeclimate/php-test-reporter/blob/v0.4.1/composer/bin/test-reporter#L8) 5.4. Version 0.3.2 seems to have PHP 5.3 array syntax. Just confirmed that my latest Travis build with the reporter at 0.3.2 finally reported the coverage data. So:

PHP >=5.5: Reporter `^0.4.2`
5.4 >= PHP < 5.5: Reporter `<=0.4.1`
PHP < 5.4: Reporter `<=0.3.2`

**Comment by localheinz** [comment]
This package obeys semantic versioning. 

According to http://semver.org/#spec-item-4

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Having said that, all is fine. 

The problem is with developers using  wildcard or the `^` operator when requiring unstable versions.

The simplest, and best solution to the problem in general is to always pin a non-stable dependency to a concrete version. 

What do you think, will that work for you?

**Comment by XedinUnknown** [comment]
@localheinz, here's an excerpt from [Composer documentation](https://getcomposer.org/doc/articles/versions.md#caret):
> The ^ operator behaves very similarly but it sticks closer to semantic versioning, and will always allow non-breaking updates. [...] For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0

What this means is that, to be very strict, in pre-stable releases, increment in a minor version number should indicate BC-breaking changes. This is not the case here. Furthermore, like I wrote above, this still would not resolve the problem of `0.4.1.` having PHP 5.4 code.

**Comment by XedinUnknown** [comment]
Pinning a non-stable dep for CC test reporter to an at least more restricted range is a _very_ good idea. However, CC docs say `dev-master`.

**Comment by localheinz** [comment]
@XedinUnknown 

For reference, also see

* https://github.com/composer/composer/pull/5343
* https://github.com/composer/composer/issues/5338

I think, though, that we can go back to supporting PHP 5.3 - as far as I can tell, the only dependency requiring PHP 5.5 is actually used for building the PHAR archive. Since that isn't needed for normal usage, we can probably sort this out. 

I think there's also another open issue in regard to providing a downloadable PHAR when tagging, going to take a look later!

**Comment by XedinUnknown** [comment]
@localheinz, not exactly sure, but from the references you included it would seem that you are agreeing with me on the points that I made. Am I right?

Please don't get me wrong: I love what CodeClimate is doing, especially for open-source projects. But I would really like to be able to depend on it just as I can depend on other great packages. Therefore, I would really appreciate stricter following of the caret operator's rules, and more care when declaring dependencies as important as the PHP version from CodeClimate.

Thanks for everything! :)

**Comment by Bonscho** [comment]
I just analyzed the latest stable source. It should be an easy task to keep it PHP 5.3 compatible. Should I provide a PR?

**Comment by XedinUnknown** [comment]
Doesn't seem like much attention is being paid to this thread by the developers of the product. Builds may be suddenly broken for a lot of people, but doesn't look like the solution is being discussed.

@Bonscho, did you also check if the _dependencies_ of the latest stable source are PHP 5.3 compatible?

**Comment by Bonscho** [comment]
@XedinUnknown, as far as I can see supporting at least PHP 5.3.9 should be possible. The highest requirements are set by symphony/console version 2.8.16 which is the latest stable relaese of the 2.x major version.

**Comment by localheinz** [comment]
@Bonscho 

> I just analyzed the latest stable source. It should be an easy task to keep it PHP 5.3 compatible. Should I provide a PR?

The problem isn't actually the code in this repository, but one of the dependencies, namely [`tm/tooly-composer-script`](https://github.com/tommy-muehle/tooly-composer-script).

See

* our [`composer.json`](https://github.com/codeclimate/php-test-reporter/blob/master/composer.json#L31)
* their [`composer.json`](https://github.com/tommy-muehle/tooly-composer-script/blob/1.0.0/composer.json#L37)

So, the re-establish compatibility with PHP 5.3 (and by that I also understand a passing build on {HP 5.3), the following would be necessary

### A

1. remove hard dependency on `tm/tooly-composer-script` (after all, it's neither needed for development, nor for production, it's only needed for creating a PHAR archive)
2. provide an alternative for packaging a phar 

For **2.**, I have no idea what the current process is for creating a PHAR archive, but I would be happy to hear more about it, I'm sure we can sort something out that doesn't require a hard dependency or a composer script

### B

1. Install dependencies on Travis, ignoring platform requirements.

Also, for both **A** and **B**, restore compatibility with PHP 5.3.

**Comment by XedinUnknown** [comment]
@localheinz, didn't really understand the *B*. Why ignore platform requirements, when everything is compatible with PHP >= 5.3.9?

**Comment by localheinz** [comment]
@XedinUnknown 

> @localheinz, not exactly sure, but from the references you included it would seem that you are agreeing with me on the points that I made. Am I right?

No, I don't agree, reciting http://semver.org/#spec-item-4:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

As it says, anything may change at any time, so there's neither a guarantee for depending parties, nor a requirement for providers of unstable packages to obey BC at any time. 

That is, I'm preaching to the choir everyday, if you depend on an unstable package, always pin it to a concrete version.

**Comment by localheinz** [comment]
@XedinUnknown 

> didn't really understand the B. Why ignore platform requirements, when everything is compatible with PHP >= 5.3.9?

Because the build will otherwise fail, trying to install a development dependency on Travis that requires PHP 5.3.

**Comment by XedinUnknown** [comment]
@localheinz, why would the build fail?

With regard to BC, I already quoted from composer docs. Caret operator permits "safe" upgrades, even for pre-stable releases. Even if this is not strictly speaking the rule of semantic versioning, it is still a standard used by many, and due to its advantages I believe that it is something to consider following. I.e. if you break BC from 0.3.2, you must release 0.4. If you break BC, from 0.4.1, release 0.5. It really isn't that hard, and you will not run out of numbers or anything. So why not give your consumers a way to always be able to automatically get non-BC-breaking fixes by depending on e.g. `^0.3.2`, if it's just that simple?

**Comment by localheinz** [comment]
@Bonscho 

> With regard to BC, I already quoted from composer docs. Caret operator permits "safe" upgrades, even for pre-stable releases.

Composer docs are one thing, but again, semantic versioning is a different thing - composer doesn't dictate what semantic versioning is, and if Jordi has a different idea, then that is fine. Of course, what we can do is make it easier for consumers who disagree and think they should be able to use the `^` operator, and #104 is going to be an attempt to do just that.

**Comment by XedinUnknown** [comment]
Amazing. Faith restored. Thank you :)

**Comment by Bonscho** [comment]
@XedinUnknown @localheinz I agree. You both are correct. But signalizing BC breaking prereleases by increasing the minor version would better the overall convenience. Just my opinion.

**Comment by Bonscho** [comment]
And of course the docs should reflect the actual usage or interpretation of the package owner of semver.

**Comment by XedinUnknown** [comment]
@Bonscho, it would appear that the interpretation of the owners is already strict semver, so that really is kind of implied already. However, the change that I personally would prefer to see in the docs is: don't recommend depending on `dev-master`, but, after committing to following the caret operator's rules, specify the lowest compatible version that users could depend on, prefixed with `^`. If one depends on a concrete version, this can cause problems with other packages, which depend on other concrete versions of your package, but are otherwise completely compatible.

**Comment by Bonscho** [comment]
@XedinUnknown You should be right *in general* (mostly). And I totally agree that recommending on `dev-master` is not the best idea ever. But just this recommendation gives me the feeling that this (or any other) package is not following semver the strict way.

**Comment by Bonscho** [comment]
Back to my initial question: Should I fix the BC breaking project sources and provide a PR? I am not the PHAR pro, but maybe this could help to make the next step into 5.3 compat.

**Comment by localheinz** [comment]
@Bonscho @XedinUnknown 

Take a look at #104, I think this should work - all we need is someone from the maintainers to confirm that they can still build their PHARs as expected, hehe!

🤓

**Comment by XedinUnknown** [comment]
Haven't actually tried the changes, but I looked through the code, and it looks good to me.

With regard to array syntax and such, i.e. the small syntax changes that are trivial but break compatibility, I maintain a [separate branch](https://packagist.org/packages/dhii/php-cs-fixer-config#dev-php-5.3) of PHP CS Fixer config specially for this purpose. Authors may want to use a similar approach.

**Comment by localheinz** [comment]
@XedinUnknown 

Same for us at @refinery29, since we have a bunch of legacy projects, we use specific configurations for different PHP versions, see https://github.com/refinery29/php-cs-fixer-config.

Also see https://github.com/codeclimate/php-test-reporter/pull/70, I'm sure a pull request would be appreciated, hehe!

**Comment by localheinz** [comment]
Build for #104 has passed, we should be good to go as soon as it has been confirmed that the PHAR can still be created as desired!

**Comment by XedinUnknown** [comment]
@localheinz, that's where I took the idea for the class from, itself. Didn't know you maintain different forks though, that's cool!

WRT #70, it's already rejected, so not sure what could be done. I myself advocate using single quotes myself. Why make PHP do additional parsing, when it's not necessary, is beyond me.

**Comment by localheinz** [comment]
@XedinUnknown 

Hehe, yes, started in 2015 with it, see here: https://github.com/refinery29/php-cs-fixer-config/commit/0564b8143a90fbc2ddf94e215073b80eeb6ae549 - there are a bunch of projects creating their own configuration, a few of them say they have been inspired by it. 

It's the easiest way, I think, to maintain a consistent coding style across a range of projects. Zend Framework, for example, uses `squizlabs/php_codesniffer`, they have a configuration at https://github.com/zendframework/zend-coding-standard.

**Comment by XedinUnknown** [comment]
@localheinz, totally agreed. It's dependable, versionable, and for the most part allows consistent re-use of the `.php_cs` file.

So, going back to CodeClimate, doesn't look like this approach is being used. May be worth considering.

**Comment by Bonscho** [comment]
Thanks a lot. Will sit back and wait the things to come. Btw I strongly prefer singel quotes over double qoutes for the given reason.

**Comment by dblandin** [comment]
Hey @Kanti (and others!),

Thank for the issue. We're winding down development on this PHP-specific reporter.

I'd recommend checking out our new test reporter and migrating to it if you're interested!

https://github.com/codeclimate/test-reporter
https://codeclimate.com/changelog/591c99570d51f6481f001291

It's decoupled from the coverage tool used to generate the report, distributed as a static binary, and has support for parallelized builds. 🎉
