### ISSUE TITLE
Minimum stability

### ISSUE THREAD

**Issue by kylekatarnls** [codeclimate/php-test-reporter#63]
Hi,

The last tagged version is now old, and so we must use dev-master (and minimum-stability dev) to get the last updates.

Can't you tag a new release?

Thanks,

**Comment by maxjacobson** [comment]
Hi @kylekatarnls -

Thanks for the ping on this. I've just tagged the latest version as `v0.4.0`.

**Comment by kylekatarnls** [comment]
Thanks!

**Comment by kylekatarnls** [comment]
Hi, please a new tag with your new symfony/console and phpunit compatibility. ;)

**Comment by maxjacobson** [comment]
Hi @kylekatarnls, thanks for the ping. We're [in the process](https://github.com/codeclimate/php-test-reporter/pull/132/files#diff-04c6e90faac2675aa89e2176d2eec7d8L5) of deprecating this codebase because we've introduced a much improved new test reporter, which doesn't need to be included as a dependency in  your project: https://github.com/codeclimate/test-reporter. Will you please try out using the new test reporter and let us know if you have any issues via https://codeclimate.com/help?

**Comment by kylekatarnls** [comment]
First project successfully migrated. Thanks.
