### ISSUE TITLE
Specify CODECLIMATE_REPO_TOKEN so coverage can be reported

### ISSUE THREAD

**Issue by localheinz** [codeclimate/php-test-reporter#93]
As you can see in https://travis-ci.org/codeclimate/php-test-reporter/jobs/191031087#L278, the environment variable `CODECLIMATE_REPO_TOKEN` hasn't been set.

There are two options

* provide it as an encrypted environment variable in `.travis.yml`
* provide it via https://travis-ci.org/codeclimate/php-test-reporter/settings

Related to #68.

💁‍♂️ For reference, see 

* https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml
* https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by localheinz** [comment]
@GordonDiggs 

Can you take a look, please? After updating to `0.4.1`, we are having issues with coverage not being reported, maybe I messed something up, not sure!

**Comment by GordonDiggs** [comment]
@localheinz the token is present in https://travis-ci.org/codeclimate/php-test-reporter/settings. I removed and re-added it to be safe

**Comment by pbrisbin** [comment]
> the environment variable CODECLIMATE_REPO_TOKEN hasn't been set.

This is expected. ENV vars set in project settings aren't visible to PRs from other owners (localheinz:fix/coverage), this is to prevent exposing secrets to non-collaborators. We run into this quite frequently.

There are a few fixes we could make:

1. Move the ENV var to .travis.yml (un-encrypted)

  We don't consider it a secret, since it's write-only and just for coverage data

1. Update the reporter to no-op if that's unset (our ruby-test-reporter does this), and accept we don't get coverage on outside contributor PRs
1. Update the _this_ travis.yml to not report if that's not present, and accept the same

We should _probably_ do 2 eventually, but 3 is a fine work-around. To do 1 or not, I don't feel strongly.

> Can you take a look, please? After updating to 0.4.1, we are having issues with coverage not being reported

Is it just this missing ENV thing, or something else?

**Comment by GordonDiggs** [comment]
@localheinz I have the token in the `yml` file now. When I look at the payloads on our end, the branch is showing up as `(detached from 3ce66aa)` instead of `master` (or the feature branch). Is that something you could look into?

**Comment by localheinz** [comment]
@GordonDiggs 

To be honest, I am quite unsure at the moment why coverage seems to be not reported from Travis.

Here's what I just ran

```
$ vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
$ CODECLIMATE_REPO_TOKEN=... ./composer/bin/test-reporter
```

Let's see if the coverage shows up.

**Comment by GordonDiggs** [comment]
I believe this is working now!
