### ISSUE TITLE
Failed to load external entity

### ISSUE THREAD

**Issue by carbontwelve** [codeclimate/php-test-reporter#96]
My `travis.yaml` is almost identical to the one for this project and yet I get the horrible error output that clover.xml is not found: https://travis-ci.org/carbontwelve/tapestry/jobs/191265093#L269

```
PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity "/home/travis/build/carbontwelve/tapestry/build/logs/clover.xml" in /home/travis/build/carbontwelve/tapestry/vendor/satooshi/php-coveralls/src/Satooshi/Bundle/CoverallsV1Bundle/Api/Jobs.php on line 53
```

The command `"vendor/bin/phpunit --coverage-clover=build/logs/clover.xml"` exited with 0 and is the same command that php-test-reporter uses itself.

As an aside to this, shouldn't the tool provide a pretty error and exit when it first identifies that it cant find the xml file?

**Comment by jhabdas** [comment]
After having troubles with the current docs and running into #53 I'm now stuck on this too. Will update once I've figured it out. But jebus I'm starting to feel like I just hit the multiball stage in pinball machine without any flappers.

**Comment by jhabdas** [comment]
This parsing error occurs because the `php-coveralls` dependency is not able to find `build/logs/clover.xml`.

Here's the [relevant code](https://github.com/satooshi/php-coveralls/blob/d5124af8bd6464144d550906cce46bd0df78f428/src/Satooshi/Bundle/CoverallsV1Bundle/Api/Jobs.php#L53) from the dependency:

```php
$xml = simplexml_load_file($cloverXmlPath);
```

To resolve this it must be able to find the file. Places to start looking depending on your setup include `.travis.yml` or `phpunit.xml.dist`, or possibly both. Note the [CodeClimate PHP docs](https://docs.codeclimate.com/docs/php) show a simple use case of calling `phpunit` like:

```shell
phpunit --coverage-clover build/logs/clover.xml
```

Which would would then be used used to generate the XML file consumed by coveralls. Also of interest is the `--coverage-report` flag made available by `test-reporter`, like:

```yml
after_success:
  - if [[ "$REPORT_COVERAGE" == "true" ]] ; then ./vendor/bin/test-reporter --coverage-report=build/logs/clover.xml ; fi
```

**Comment by dblandin** [comment]
Hey @carbontwelve,

Thank for the issue. We're winding down development on this PHP-specific reporter.

I'd recommend checking out our new test reporter and migrating to it if you're interested!

https://github.com/codeclimate/test-reporter
https://codeclimate.com/changelog/591c99570d51f6481f001291

It's decoupled from the coverage tool used to generate the report, distributed as a static binary, and has support for parallelized builds. 🎉

**Comment by carbontwelve** [comment]
@dblandin hey thank you for following up on this I will certainly have a look at the new test reporter.
